# -*- coding: utf-8 -*-
"""Heart_disease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WtXZ7_-JgyTizWD25S7PHf2z7R15gonZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

data = pd.read_csv('/content/heart_disease_data.csv')

corr=data.corr()

data['target'].value_counts()

X = data.drop(['target'],axis=1)
Y = data['target']

X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

model=LogisticRegression()
model.fit(X_train,y_train)

prediction = model.predict(X_test)
print(prediction)

eval = accuracy_score(y_test,prediction)
print(eval)

prediction = model.predict(X_train)
eval = accuracy_score(y_train,prediction)
print(eval)

input_data=(60,1,0,125,258,0,0,141,1,2.8,1,1,3)
input_data_array = np.asarray(input_data)
input_data_reshape = input_data_array.reshape(1,-1)
prediction = model.predict(input_data_reshape)
print(prediction)